[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
# startCommand = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"[deploy]
# startCommand = "php artisan config:clear && php artisan route:clear && php artisan view:clear && php artisan serve --host=0.0.0.0 --port=$PORT"
# startCommand = "php -v && echo 'PHP WORKS' && sleep 60"
# startCommand = "composer dump-autoload && php artisan --version && sleep 60"
# startCommand = "php artisan --version && echo 'LARAVEL WORKS' && sleep 60"
# startCommand = "cd public && php -S 0.0.0.0:$PORT index.php"
# startCommand = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8080"
# startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
startCommand = "php artisan config:clear && php artisan cache:clear && php artisan serve --host=0.0.0.0 --port=8080"

[environment]
APP_ENV = "local"
APP_DEBUG = "true"

# Database Configuration untuk MySQL
DB_CONNECTION = "mysql"
DB_HOST = { from = "MYSQLHOST" }
DB_PORT = { from = "MYSQLPORT" }
DB_DATABASE = { from = "MYSQLDATABASE" }
DB_USERNAME = { from = "MYSQLUSER" }
DB_PASSWORD = { from = "MYSQLPASSWORD" }
