[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
# startCommand = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
startCommand = "sleep 10 && php artisan config:clear && php artisan cache:clear && php artisan serve --host=0.0.0.0 --port=$PORT"

[environment]
APP_ENV = "production"
APP_DEBUG = "false"

# Database Configuration untuk MySQL
DB_CONNECTION = "mysql"
DB_HOST = { from = "MYSQLHOST" }
DB_PORT = { from = "MYSQLPORT" }
DB_DATABASE = { from = "MYSQLDATABASE" }
DB_USERNAME = { from = "MYSQLUSER" }
DB_PASSWORD = { from = "MYSQLPASSWORD" }
